### ISSUE TITLE
look_upVGS returns "nan" if vds is capitalised 

### ISSUE THREAD

**Issue by dn9glch** [dreoilin/pygmid#1]
look_upVGS returns "nan" if vds is capitalised 
VGS_nch = NCH.look_upVGS(GM_ID = 16, VDS = 1.5, L = 1) WONT WORK
VGS_nch = NCH.look_upVGS(GM_ID = 16, vds = 1.5, L = 1) WILL WORK

**Comment by dreoilin** [comment]
Issue fixed in most recent commit.

lookupVGS kwargs capitalised
