### ISSUE TITLE
Not returning GM, GDS independently from the lookup table however returns GM_GDS

### ISSUE THREAD

**Issue by avlsi** [dreoilin/pygmid#23]
gds  = nmos.look_up('GDS',  GM_ID=gm_id, L=L VGS=VGS_nmos, VDS=VDS,VSB=VSB)
gm  = nmos.look_up('GM',  GM_ID=gm_id, L=L VGS=VGS_nmos, VDS=VDS,VSB=VSB)
returns []

whereas 
gm_gds = nmos.look_up('GM_GDS',  GM_ID=gm_id, L=L VGS=VGS_nmos, VDS=VDS,VSB=VSB)
returns a value, Ex: 160.

Is there anything missing in the function or the way it's used?

**Comment by dreoilin** [comment]
Hi avlsi,

Your usage is incorrect. You can't directly lookup GDS or GM from the lookup function against gm/ID .

Usually we find an Ibias from our GBW specification.

Then you can lookup:

```
GDS = Ibias * nmos.look_up('GDS_ID', GM_ID=gm_id, ........)
GM =  Ibias * gm_id
```

You can email me for a common source design example

Cian

**Comment by avlsi** [comment]
I did try GDS_W and its working. Thanks for the feedback.
gds1 = nmos.look_up('GDS_W',VGS=VGS1,VDS=VDS1,L=L)
VEA1 = JD1/gds1
