### ISSUE TITLE
Few fixes needed in order to run test files

### ISSUE THREAD

**Issue by ZeRuiCustodio** [dreoilin/pygmid#24]
Hello, 

  I have just cloned the latest release v1.2.10 and want to re-start checking how well I can replicate the examples from B. Murmann's book with your pygmid. 
  At the moment I found the following issues:
  - utility.py, line 28, np.asscalar(lk['TEMP']) has been removed from latest numpy releases. I have replaced it with float64(lk['TEMP']).
  - debug_lookup.py tries to load a model which does not exist "NCH = lut('tsmcN65_n25.pkl')". I have changed the code to do the following:
"import os
file_LUT = os.path.dirname(__file__) + '\\..\\files\\180nch.mat'
NCH = lk(file_LUT)  # load MATLAB data into pygmid lookup object"
  - debug_utility.py, the XTRACT mode is not set to "1" on the 2nd test (TypeError: XTRACT() missing 1 required positional argument: 'mode')

  Would be nice if this issues would be fixed for anyone trying the tool in the future. 

  Best regards.

**Comment by dreoilin** [comment]
Thanks ZeRuiCustodio.

These issues will be fixed for the next release

Cian

**Comment by ZeRuiCustodio** [comment]
Hi @dreoilin,

 Great, thank you!

**Comment by dreoilin** [comment]
- Deprecated np.asscalar() has been replaced with (  ).item()
- It is up to the user to appropriately specify a path for the debug scripts. They are just templates for the user and not proper tests. I have added a comment to make this clear
- Mode specified explicitly in the debug_utility script
