### ISSUE TITLE
Lookup function fails when giving ID_W as ratio input ("varkeys") in order to obtain GM_ID ("outkey"). 

### ISSUE THREAD

**Issue by ZeRuiCustodio** [dreoilin/pygmid#25]
Hi @dreoilin ,

  I am comparing two scripts, one using an older release of the "pygmid" and the most recent release, and unfortunately I just found an error which does not allow me with the latest release to obtain GM_ID when providing ID_W as input ratio. This works fine in the old release and of course in Matlab version of the tool.

This can be replicated by using your debug_lookup.py script and just run the following code:
id_w = NCH.look_up('ID_W', GM_ID=15, L=0.18)
print(id_w) # 180nch.mat --> 1.1593054698255034e-05
# ------------------------
gm_id = NCH.look_up('GM_ID', ID_W=1.159e-05, L=0.18)
print(gm_id)

Which results in the following error message:
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[9], line 1
----> 1 gm_id = NCH.look_up('GM_ID', ID_W=1.159e-05, L=0.18)
      2 print(gm_id)

File path\anaconda3\envs\pygmid\lib\site-packages\pygmid\Lookup.py:170, in Lookup.look_up(self, out, **kwargs)
    168     return []
    169 # appropriate lookup function is called with modefuncmap dict
--> 170 y = self.__modefuncmap.get(mode) (outkeys, varkeys, vararg, pars, **ipkwargs)
    172 return y

File path\anaconda3\envs\pygmid\lib\site-packages\pygmid\Lookup.py:285, in Lookup._RatioVRatioLK(self, outkeys, varkeys, vararg, pars, **ipkwargs)
    283                 print('Crossing warning')
    284                 return []
--> 285             output[i, j] = interp1(x_right, y_right, **ipkwargs)(xdesired[j])
    287 output = np.squeeze(output)
    289 return output

UnboundLocalError: local variable 'x_right' referenced before assignment

This is quite an important feature for the tool, specially when working in deep weak inversion. Can you please have a look at why this feature stopped working?

Thank you in advance.

**Comment by ZeRuiCustodio** [comment]
Hi, 

  So just tried to obtain GM_ID using as input ratio parameter GM_W and the same error occurs. It seems that for the Lookup Ratio Vs Ratio, the only input ratio working is GM_ID. Any other ratio results in the same error.

Kind regards, 

  José

**Comment by ZeRuiCustodio** [comment]
Hello again, 

  Replacing the current release function "_RatioVRatioLK" by the one I have in the old release, allows input ratios, like ID_W and GM_W to work again when trying to find GM_ID.

#-----------------------------------------
Here is the old version:
    def _RatioVRatioLK(self, outkeys, varkeys, vararg, pars, **ipkwargs):
        """
        Lookup for Mode 3

        Args:
            outkeys: list of keys for desired output e.g ['GM', 'ID'] for 'GM_ID'
            varkeys: list of keys for ratio input e.g ['GM', 'ID'] for 'GM_ID'
            pars: dict containing L, VGS, VDS and VSB data
        Output:
            output: interpolated data specified by outkeys. Squeezed to remove extra
                    dimensions
        """
        # print(f"!!!Entered Lookup Ratio Vs Ratio LK Function()!!!")
        ipnkwargs = {'bounds_error': False,
                    'fill_value' : None} # JBA
        # print(f"Interpn: fill_value changed to 'None' --> extrapolate!!!!")

        with np.errstate(divide='ignore',invalid='ignore'):
            # unpack outkeys and ydata
            num, den = outkeys
            ydata =  self.__DATA[num]/self.__DATA[den]
            # unpack varkeys and xdata
            num, den = varkeys
            xdata = self.__DATA[num]/self.__DATA[den]

        xdesired = np.atleast_1d(vararg)

        points = (self.__DATA['L'], self.__DATA['VGS'], self.__DATA['VDS'],\
            self.__DATA['VSB'])
        xi_mesh = np.array(np.meshgrid(pars['L'], pars['VGS'], pars['VDS'], pars['VSB'], indexing='ij'))
        xi = np.rollaxis(xi_mesh, 0, 5)
        xi = xi.reshape(int(xi_mesh.size/4), 4)

        # x = interpn(points, xdata, xi).reshape(len(np.atleast_1d(pars['L'])), \
        #     len(np.atleast_1d(pars['VGS'])), len(np.atleast_1d(pars['VDS'])),\
        #          len(np.atleast_1d(pars['VSB'])))

        x = interpn(points, xdata, xi, **ipnkwargs).reshape(len(np.atleast_1d(pars['L'])), \
            len(np.atleast_1d(pars['VGS'])), len(np.atleast_1d(pars['VDS'])),\
                 len(np.atleast_1d(pars['VSB'])))

        # y = interpn(points, ydata, xi).reshape(len(np.atleast_1d(pars['L'])), \
        #     len(np.atleast_1d(pars['VGS'])), len(np.atleast_1d(pars['VDS'])),\
        #          len(np.atleast_1d(pars['VSB'])))

        y = interpn(points, ydata, xi, **ipnkwargs).reshape(len(np.atleast_1d(pars['L'])), \
            len(np.atleast_1d(pars['VGS'])), len(np.atleast_1d(pars['VDS'])),\
                 len(np.atleast_1d(pars['VSB'])))

        x = np.array(np.squeeze(np.transpose(x, (1, 0, 2, 3))))
        y = np.array(np.squeeze(np.transpose(y, (1, 0, 2, 3))))

        if x.ndim == 1:
            x.shape += (1,)
            y.shape += (1,)

        dim = x.shape
        output = np.zeros((dim[1], len(xdesired)))
        # ipkwargs = {'fill_value' : np.nan, 'bounds_error': False}  # Original
        ipkwargs = {'fill_value' : "extrapolate", 'bounds_error': False}  # JBa
        # print(f'Interp1d: fill_value changed to extrapolate!!!!')
        for i in range(0, dim[1]):
            for j in range(0, len(xdesired)):
                m = max(x[:, i])
                idx = np.argmax(x[:, i])
                if (xdesired[j] > m):
                    print(f'Look up warning: {num}_{den} input larger than maximum! Output is NaN')
                if (num.upper() == 'GM') and (den.upper() == 'ID'):
                    x_right = x[idx:-1, i]
                    y_right = y[idx:-1, i]
                    output[i, j] = interp1d(x_right, y_right, **ipkwargs)(xdesired[j])
                elif (num.upper() == 'GM') and (den.upper() == 'CGG') or (den.upper() == 'CGG'):
                    x_left = x[1:idx, i]
                    y_left = y[1:idx, i]
                    output[i, j] = interp1d(x_left, y_left, **ipkwargs)(xdesired[j])
                else:
                    crossings = len(np.argwhere(np.diff(np.sign(x[:,i]-xdesired[j]+eps))))
                    if crossings > 1:
                        print('Crossing warning')
                        return []
                output[i, j] = interp1d(x[:,i], y[:, i], **ipkwargs)(xdesired[j])

        output = np.squeeze(output)

        return output

**Comment by dreoilin** [comment]
![image](https://github.com/dreoilin/pygmid/assets/43523688/51daf536-faaf-4b6c-9ab1-0d68233998d4)

Thanks for spotting this. 1-D interpolation at the end of RatioVsRatio. The fix will be uploaded later today

Cian

**Comment by ZeRuiCustodio** [comment]
Hi @dreoilin,

  Thank you very much!
