### ISSUE TITLE
New location of original starter kit

### ISSUE THREAD

**Issue by bmurmann** [dreoilin/pygmid#27]
Please point to https://github.com/bmurmann/Book-on-gm-ID-design/tree/main/starter_kit, since https://web.stanford.edu/~murmann is no longer active. Thanks!

**Comment by dreoilin** [comment]
Hi, the link in the readme now points to https://github.com/bmurmann/Book-on-gm-ID-design/tree/main/starter_kit . This change will appear on PyPI after the next version update.
